- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Connection.cs
- RabbitMQ.Stream.Client/MetaData.cs
- RabbitMQ.Stream.Client/PeerProperties.cs
- RabbitMQ.Stream.Client/SaslAuthenticateRequest.cs
- RabbitMQ.Stream.Client/WireFormatting.cs
* WireFormatting allocation reductions.
* async/await optimizations.
> Allocation and async optimizations

- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/ClientExceptions.cs
- RabbitMQ.Stream.Client/OpenResponse.cs
- RabbitMQ.Stream.Client/ResponseCode.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/ClientTests.cs
- Tests/SystemTests.cs
- Add Virtual host configuration
- Add ClientException to handle the protocol Exceptions
- Add tests
Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/26
> Add Virtual Host Configuration

- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Consumer.cs
- Tests/ConsumerSystemTests.cs
- Tests/Utils.cs
Expose the `StoreOffset` on the `Consumer` Class
```csharp
MessageHandler = async (consumer, ctx, message) =>
{
consumer.StoreOffset(ctx.Offset);
```
> Add consumer StoreOffset

- .github/workflows/nuget.yml
- .gitignore
- Docker/Dockerfile
- Makefile
- README.md
- Tests/ConsumerSystemTests.cs
- Tests/Tests.csproj
- Tests/Utils.cs
- add Make file
- Add docker image 
- `make run-test-in-docker` to simulate the CI
- Add `codecov` integration
> Improve test suite

- RabbitMQ.Stream.Client/Consumer.cs
- RabbitMQ.Stream.Client/Producer.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/ClientTests.cs
- Tests/ConsumerSystemTests.cs
- Tests/ProducerSystemTests.cs
- Tests/SystemTests.cs
- Implement `System.DeleteStream/1`
- add DeleteStream to the tests
> Implement DeleteStream

- RabbitMQ.Stream.Client/Consts.cs
- RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/ClientTests.cs
- Tests/SystemTests.cs
Closes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/38
Add new API bool stream.StreamExists/1
> Make stream creation idempotent

- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Connection.cs
- RabbitMQ.Stream.Client/SslHelper.cs
- RabbitMQ.Stream.Client/SslOption.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/SystemTests.cs
Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/37
> Add TLS support

- README.md
> Documentation first part

- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Connection.cs
- Tests/ClientTests.cs
Add the exception during the socket reading in this case the notify close is always raised
> Add the exception during the socket reading

- README.md
- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Consumer.cs
- RabbitMQ.Stream.Client/INamedEntity.cs
- RabbitMQ.Stream.Client/Producer.cs
- RabbitMQ.Stream.Client/RoutingClient.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
Added connection_name property for consumer/producer/locator.
> #35 Set TCP connection name

- Examples/CompressCodecs/README.md
- Examples/CompressCodecs/lz4/README.md
- Examples/CompressCodecs/lz4/StreamLz4Codec.cs
- README.md
Part of https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/59
> Implement lz4 codec example

- Tests/ApiApproval.Approve.verified.txt
- Tests/ProducerSystemTests.cs
Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/81
> Refactor MixProducer test

- Makefile
- RabbitMQ.Stream.Client/ClientExceptions.cs
- RabbitMQ.Stream.Client/Compression.cs
- RabbitMQ.Stream.Client/Connection.cs
- RabbitMQ.Stream.Client/Consumer.cs
- RabbitMQ.Stream.Client/Create.cs
- RabbitMQ.Stream.Client/IClient.cs
- RabbitMQ.Stream.Client/Message.cs
- RabbitMQ.Stream.Client/OpenRequest.cs
- RabbitMQ.Stream.Client/PeerProperties.cs
- RabbitMQ.Stream.Client/Producer.cs
- RabbitMQ.Stream.Client/QueryOffsetRequest.cs
- RabbitMQ.Stream.Client/RoutingClient.cs
- RabbitMQ.Stream.Client/SaslAuthenticateRequest.cs
- RabbitMQ.Stream.Client/SaslAuthenticateResponse.cs
- RabbitMQ.Stream.Client/SaslHandshakeRequest.cs
- RabbitMQ.Stream.Client/StoreOffsetRequest.cs
- RabbitMQ.Stream.Client/StreamSpec.cs
- RabbitMQ.Stream.Client/SubEntryPublish.cs
- RabbitMQ.Stream.Client/Subscribe.cs
- RabbitMQ.Stream.Client/TuneRequest.cs
- RabbitMQ.Stream.Client/WireFormatting.cs
- Tests/ApiApproval.Approve.verified.txt
> Various refactorings

- .github/workflows/main.yaml
> Use official RMQ image

- .github/workflows/main.yaml
- .github/workflows/nuget.yml
> Use different method to get container id

- Examples/Reliable/ReliableProducer.cs
- README.md
- RabbitMQ.Stream.Client/Consumer.cs
- RabbitMQ.Stream.Client/Producer.cs
- RabbitMQ.Stream.Client/Reliable/ReliableProducer.cs
- RabbitMQ.Stream.Client/RoutingClient.cs
- Tests/ClientTests.cs
- Tests/Utils.cs
- tools/versions.json
Fixes #77
Change some more timeouts
> Replace with TimeSpan

- README.md
I assume this isn't that common but some people might want this example in the repo for quick reference.
> Add client cert example to readme

- RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
- RabbitMQ.Stream.Client/Reliable/Producer.cs
- RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
- Tests/ReliableTests.cs
Expose MessagesBufferSize to the High Level producer
> Expose MessagesBufferSize

- RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
- RabbitMQ.Stream.Client/RasSuperStreamConsumer.cs
- RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/SuperStreamConsumerTests.cs
- Tests/UsabilityTests.cs
To be complainat with the other names
> Rename the SuperStreamConsumer to RawSuperStreamConsumer

- README.md
> Add documentation for logging

- Examples/SuperStream/Costants.cs
- Examples/SuperStream/README.md
- Examples/SuperStream/Start.cs
- Examples/SuperStream/SuperStream.csproj
- Examples/SuperStream/SuperStreamConsumer.cs
- Examples/SuperStream/SuperStreamProducer.cs
- README.md
Complete Super Stream Single Active consumer example
ref https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/196
> Complete Super Stream Single Active consumer example

- RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
- RabbitMQ.Stream.Client/AMQP/Header.cs
- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/Connection.cs
- RabbitMQ.Stream.Client/Consts.cs
- RabbitMQ.Stream.Client/MetaData.cs
- RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
- RabbitMQ.Stream.Client/RawConsumer.cs
- RabbitMQ.Stream.Client/RawProducer.cs
- RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
- RabbitMQ.Stream.Client/Reliable/Producer.cs
- Tests/ReliableTests.cs
Add the link to the rabbitmq repo for a critical issue
Deal with some old TODO
Add more detailed error messages
Add some documentation
> Change the error messages 

- Tests/SuperStreamConsumerTests.cs
- Tests/SuperStreamProducerTests.cs
> Add TaskCompletionSource to wait the test instead

- RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
- RabbitMQ.Stream.Client/AMQP/Annotations.cs
- RabbitMQ.Stream.Client/AMQP/ApplicationProperties.cs
- RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
- RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
- RabbitMQ.Stream.Client/Reliable/Consumer.cs
- RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
- RabbitMQ.Stream.Client/Reliable/Producer.cs
- RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
Properly format docstrings where possible; remove some redundant qualifiers
> Minor doc/codestyle cleanup

- Examples/SuperStream/Start.cs
- Examples/SuperStream/SuperStream.csproj
- Examples/SuperStream/SuperStreamConsumer.cs
- Examples/SuperStream/SuperStreamProducer.cs
- RabbitMQ.Stream.Client/Client.cs
Check if the result is null. Add a log when the write fails. Improve the super stream example
> Small super stream improvements

- .gitignore
- Makefile
- README.md
- docs/Documentation/README.md
- docs/asciidoc/.gitignore
- docs/asciidoc/api.adoc
- docs/asciidoc/sample-application.adoc
- docs/asciidoc/super-streams.adoc
> Make github pages

- RabbitMQ.Stream.Client/Client.cs
- RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
- RabbitMQ.Stream.Client/StreamStats.cs
- RabbitMQ.Stream.Client/StreamStatsRequest.cs
- RabbitMQ.Stream.Client/StreamStatsResponse.cs
- RabbitMQ.Stream.Client/StreamSystem.cs
- Tests/SystemTests.cs
- docs/asciidoc/index.adoc
- docs/asciidoc/query-stream.adoc
Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/208
[Here](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/242/files#diff-486e27997e79ea2fbc47a1d0c9b5937d98ca4cd7f3c31bf1c050e410c154ac94R121) you can find the test
> Implement stream stats

- RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
> Use UtcDateTime

- .ci/versions.json
- Directory.Packages.props
- Tests/SacTests.cs
- Tests/SuperStreamProducerTests.cs
* Update NuGet packages
* Update some xunit assertions
> Misc updates

- RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
Hi,
Just one more small addition.
It does the same job, but in a more simple and idiomatic way.
> Iterate _lastOffsetConsumed in a more simple way

- RabbitMQ.Stream.Client/RawConsumer.cs
- Tests/RawConsumerSystemTests.cs
- docs/StreamFilter/StreamFilter/FilterConsumer.cs
- docs/StreamFilter/StreamFilter/FilterProducer.cs
- docs/StreamFilter/StreamFilter/FilterSuperStreamProducer.cs
- docs/StreamFilter/StreamFilter/README.md
- docs/asciidoc/advanced-topics.adoc
- docs/asciidoc/index.adoc
> Add filter documentation

- docs/Documentation/ConsumerUsage.cs
- docs/asciidoc/api.adoc
> remove System.IO.Hashing dependency

- RabbitMQ.Stream.Client/Reliable/Consumer.cs
- docs/Documentation/ConsumerUsage.cs
- docs/Documentation/Documentation.csproj
- docs/asciidoc/api.adoc
Add  CRC documentation. Just more details
> documentation [skip ci]

- .ci/versions.json
- .github/workflows/build-test.yaml
- README.md
- Tests/FromToAMQPTests.cs
* Update ci to `3.13.0-beta.6`
* Starting from `rabbitmq:3.13.0-beta.5` long strings are not converted to string but to byte[] due to https://github.com/rabbitmq/rabbitmq-server/pull/5077
Change the `Amqp10ShouldReadTheAmqp019Properties` to work with RabbitMQ >= 3.13.0-beta.5
> update rabbitmq version for ci

- RabbitMQ.Stream.Client/StreamSystem.cs
- Dispatch to all the pool connections
Fixes the issue raised by @vivek-singh2 @lngvivek here: https://github.com/lngvivek/UpdateSecretIssueTest/blob/main/README.md
Do you have the chance to test it?
@vivek-singh2 @lngvivek
> Dispatch the update secrets

- Directory.Packages.props
- RabbitMQ.Stream.Client.PerfTest/RabbitMQ.Stream.Client.PerfTest.fsproj
- RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
- Tests/Tests.csproj
- docs/Documentation/Documentation.csproj
- docs/ReliableClient/ReliableClient.csproj
- docs/StreamFilter/StreamFilter/StreamFilter.csproj
- docs/SuperStream/SuperStream.csproj
> Add support build for net8

- RabbitMQ.Stream.Client/IConsumer.cs
- RabbitMQ.Stream.Client/IProducer.cs
- Tests/RawConsumerSystemTests.cs
- Tests/RawProducerSystemTests.cs
- Tests/SuperStreamConsumerTests.cs
- Tests/SuperStreamProducerTests.cs
The bug was introduced on https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/406
> Fix ToString function in case partitions is null.

- RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
> #415 switch to license expression

- docs/ReliableClient/README.md
Fixed typos and added links to relevant code sections
Fixes #429
> Update ReliableClient Readme
