rabbitmq/rabbitmq-stream-dotnet-client

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/CloseResponse.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/Consumer.cs
RabbitMQ.Stream.Client/Create.cs
RabbitMQ.Stream.Client/DeclarePublisherResponse.cs
RabbitMQ.Stream.Client/Delete.cs
RabbitMQ.Stream.Client/DeletePublisherResponse.cs
RabbitMQ.Stream.Client/Deliver.cs
RabbitMQ.Stream.Client/ICommand.cs
RabbitMQ.Stream.Client/Message.cs
RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/OpenResponse.cs
RabbitMQ.Stream.Client/PeerProperties.cs
RabbitMQ.Stream.Client/Producer.cs
RabbitMQ.Stream.Client/Publish.cs
RabbitMQ.Stream.Client/PublishConfirm.cs
RabbitMQ.Stream.Client/PublishError.cs
RabbitMQ.Stream.Client/QueryOffsetResponse.cs
RabbitMQ.Stream.Client/QueryPublisherResponse.cs
RabbitMQ.Stream.Client/SaslAuthenticateResponse.cs
RabbitMQ.Stream.Client/SaslHandshakeResponse.cs
RabbitMQ.Stream.Client/Subscribe.cs
RabbitMQ.Stream.Client/Tune.cs
RabbitMQ.Stream.Client/TuneRequest.cs
RabbitMQ.Stream.Client/Unubscribe.cs
Tests/ClientTests.cs

* Removed channels from Client and Connection. This reduced the number of tasks that need be running and gets rid of double-buffering for frames sent/received.
* Added a bounded channel on the Producer to batch `Publish` messages sent.
* Made the Request operations generic so it's now `Request<TIn, TOut>`
* Added a pooled `IValueTaskSource` to reuse `ValueTask` objects for Request operations.
* Added generic optimizations for the `Connection.Write` method for better code generation and to eliminate struct boxing for ICommand objects.
* Added array pooling for `ulong` arrays in message confirmations and for frame handling. Arrays are returned after confirmations have been processed and after frames have been handled.

Allocation reductions and CPU/Task optimizations

---

RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ClientTests.cs
Tests/SystemTests.cs

- Add the response code error.
- Handle when the stream does not exist.
- Producer Creation: Raise an Exception when the stream does not exist
- Add tests
Fix the following error when a stream does not exist.
Code:
```csharp
var stream = "StreamNotExist"
var producer = await system.CreateProducer(
new ProducerConfig
{
Reference = "producer",
Stream = stream,
ConfirmHandler = conf => { }
});
```
error
```csharp
System.TimeoutException: The operation has timed out.
at RabbitMQ.Stream.Client.ManualResetValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/Client.cs:line 463
at RabbitMQ.Stream.Client.Client.Request[TIn,TOut](Func`2 request, Int32 timeout) in …
```

Refactor QueryMetadata

---

.github/workflows/nuget.yml
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Consumer.cs
RabbitMQ.Stream.Client/Producer.cs
RabbitMQ.Stream.Client/StreamSystem.cs
RabbitMQ.Stream.Client/Unubscribe.cs
Tests/ClientTests.cs
Tests/ConsumerSystemTests.cs
Tests/ProducerSystemTests.cs
Tests/SystemTests.cs
Tests/Utils.cs

Implement `IDisposble` method for `Producer` and `Consumer` class.
That's the idea:
```csharp
using var producer1 = await system.CreateProducer(
new ProducerConfig
{
Reference = Guid.NewGuid().ToString(),
Stream = stream,
ConfirmHandler = conf => { }
});
await producer1.Send(1, message);
```
user can also call directly `Close()` to remove the producer from the server ( not mandatory btw)
for `Consumer`:
```csharp
using var consumer = await system.CreateConsumer(
new ConsumerConfig
{
Reference = "consumer",
Stream = stream,
MessageHandler = async (consumer, ctx, message) => { await Task.CompletedTask; }
});
```
user can also call directly `Close()` to remove the consumer from the server ( not mandatory btw)

Implement IDisposable method to Producer and Consumer Class

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/Consumer.cs
RabbitMQ.Stream.Client/ICommand.cs
RabbitMQ.Stream.Client/Producer.cs
Tests/ClientTests.cs
Tests/ConsumerSystemTests.cs
Tests/ProducerSystemTests.cs
Tests/Utils.cs

- Make the writer thread-safe
- Refactor a bit the tests
- Add `GenericProtocolException` to handle the protocol exceptions from the `ResponseCode` protocol

Refactor tests 

---

RabbitMQ.Stream.Client.PerfTest/Program.fs
RabbitMQ.Stream.Client.PerfTest/README.md
RabbitMQ.Stream.Client.PerfTest/RabbitMQ.Stream.Client.PerfTest.fsproj
rabbitmq-stream-dotnet-client.sln

Just a small refactor.  
- Changed the name to `RabbitMQ.Stream.Client.PerfTest` which is more appropriate. 
- Create the `dotnet-perftest`

Rename solution CMD to PerfTest

---

.github/workflows/test.yaml

nuget.yaml: the nuget push is executed only when there is a TAG
test.yaml: it does not contain the nuget push anymore
Closes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/49

Split Test and NuGet Push

---

RabbitMQ.Stream.Client.PerfTest/Program.fs
RabbitMQ.Stream.Client/Producer.cs
Tests/Utils.cs

A small refactor to hide the TCP client. 
The user should not access the client directly.

hide the tcp client

---

RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ConsumerSystemTests.cs

closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/68
query the consumer offset position with: `await system.QueryOffset(consumerName, stream)`
example:
```csharp
const string consumerName = "myConsumer";
var consumer = await system.CreateConsumer(
new ConsumerConfig
{
Reference = consumerName,
Stream = stream,
OffsetSpec = new OffsetTypeOffset(await system.QueryOffset(consumerName, stream)),
```

Expose query_offest

---

RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/ResponseCode.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ConsumerSystemTests.cs
Tests/Utils.cs

Add specific exception in case the offset does not exist
fix the ConsumerQueryOffset test.

Handle offset not found

---

.github/workflows/main.yaml
.github/workflows/nuget.yml
Docker/Dockerfile
RabbitMQ.Stream.Client.PerfTest/RabbitMQ.Stream.Client.PerfTest.fsproj
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Consts.cs
RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
Tests/ApiApproval.Approve.verified.txt
Tests/ApiApproval.cs
Tests/Tests.csproj

Update versions to beta.4
Re-instate the ApiApproval test.
Fixes #24

Update all projects to net6.0

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/Consumer.cs
RabbitMQ.Stream.Client/Producer.cs
Tests/Amqp10Tests.cs
Tests/ApiApproval.Approve.verified.txt
Tests/ClientTests.cs
Tests/ConsumerSystemTests.cs
Tests/PermissionTests.cs
Tests/ProducerSystemTests.cs
Tests/StreamSpecTests.cs
Tests/SystemTests.cs
Tests/UnitTests.cs
Tests/Utils.cs

When the tcp connection is forced the client sets the status as closed.
Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/97
See the comment on https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/97#issue-1189533103 or the test `CloseProducerConsumerAfterForceCloseShouldNotRaiseError` to reproduce the error.

Change the way to decide when the client socket is open

---

README.md
RabbitMQ.Stream.Client/StreamSpec.cs
Tests/ApiApproval.Approve.verified.txt
Tests/SystemTests.cs

added configuration for MaxSegmentSizeBytes (issue #105)

Max segment size

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Consumer.cs
Tests/SystemTests.cs

When the consumer is removed from the server for some reason the call Unsubscribe could fail.
This fix avoids to wait too much time in case the server doesn't respond.

Fix close consumer

---

RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
RabbitMQ.Stream.Client/Version.cs

This removes a build step that would result in a modified file every time.
The version shown is what MinVer sets as the "ProductVersion" assembly attribute. It's also what you see when you right-click on the `.dll`

Get version via reflection

---

RabbitMQ.Stream.Client/RoutingClient.cs
Tests/UnitTests.cs

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/125

Change the DNS validation

---

RabbitMQ.Stream.Client/Client.cs

Noticed that our heartbeat was 0 when we set it to 60. This fixes that.
Not sure if it's totally okay since timespans can be negative and casting negatives to `uint` will produce big numbers. Anyhow, maybe that's an edge case that shouldn't be covered :D

Fix a bug with Heartbeat values >59s

---

README.md
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/ReliableProducer.cs
Tests/ReliableTests.cs

Make timeout configurable
Add some descriptions to enum cases

Improved client timeout handling

---

Examples/Performances/BatchVsBatchSend.cs
Examples/Performances/Performances.csproj
Examples/Performances/Program.cs
README.md
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Producer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/ReliableProducer.cs
Tests/ProducerSystemTests.cs
Tests/ReliableTests.cs

Closes #136
Using this gist: https://gist.github.com/Gsantomaggio/cd5b0734225d3fab9ed013d634eaf005 to test the performances 
cc @ricsiLT 
Test results `Producer` and `Reliable Producer` with and without `Batch Send` :
```
*****Standard Producer Batch Send***** send time: 00:00:24.3330340, messages sent: 20000000
*****Standard Producer Send***** send time: 00:00:24.6326600, messages sent: 20000000
*****Reliable Producer Batch Send***** time: 00:00:27.2689740, messages sent: 20000000
*****Reliable Producer Send No Batch***** send time: 00:00:31.4620940, messages sent: 20000000
```
These values are excepted the good news is `Reliable Producer Batch Send` time is not so far from standard producer with `batch send`

Batch send

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/Reliable/ReliableConsumer.cs
RabbitMQ.Stream.Client/Reliable/ReliableProducer.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ReliableTests.cs

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/150
Reconnect `ReliableProducer` and/or `ReliableConsumer` in case the leader is down and if the Stream changes the topology.
Refactor The  Reliable part
How to test:
---
using a cluster with 3 nodes and:
```csharp
using System.Net;
using System.Text;
using RabbitMQ.Stream.Client;
using RabbitMQ.Stream.Client.Reliable;
namespace example;
public static class MultiEndPoints
{
public static async Task Start()
{
var config = new StreamSystemConfig()
{
UserName = "test",
Password = "test",
Endpoints = new EndPoint[]
{
new DnsEndPoint("node0", 5552),
new DnsEndPoint("node1", 5552),
new DnsEndPoint("node2", 5552),
}
};
var system = await …
```

Fix Reconnect ReliableProducer/ ReliableConsumer in case leader is down

---

RabbitMQ.Stream.Client/StreamSpec.cs
Tests/StreamSpecTests.cs
Tests/SystemTests.cs

Change definition of MaxLengthBytes stream specification from int to ulong. 
I used unsigned type because negative values don't make sense for this setting.
Fixes: #165

Change definition of MaxLengthBytes stream specification - #165

---

RabbitMQ.Stream.Client/Producer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableProducer.cs
RabbitMQ.Stream.Client/SuperStreamProducer.cs
Tests/ReliableTests.cs
Tests/SuperStreamTests.cs

Add SuperStreamConfig to enable super stream 
ReliableProducer can handle standard producers and super stream producers.  From the user's perspective, the behaviour is hidden.
Standard producer
---
```csharp
var reliableProducer = await ReliableProducer.CreateReliableProducer(new ReliableProducerConfig()
{
StreamSystem = system,
Stream = stream,
Reference = "my-reliable-producer",
ClientProvidedName = "my-reliable-producer",
ConfirmationHandler = confirmation =>
```
Super stream:
---
```csharp
var reliableProducer = await ReliableProducer.CreateReliableProducer(new ReliableProducerConfig()
{
StreamSystem = system,
Stream = stream,
Reference = "my-reliable-producer",
ClientProvidedName = "my-reliable-producer",
SuperStreamConfig …
```

Implement SuperStream for ReliableProducer

---

.ci/versions.json
Examples/Performances/BatchVsBatchSend.cs
RabbitMQ.Stream.Client.PerfTest/Program.fs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/StreamSystem.cs
RabbitMQ.Stream.Client/SuperStreamConsumer.cs
Tests/PermissionTests.cs
Tests/RawConsumerSystemTests.cs
Tests/RawProducerSystemTests.cs
Tests/ReliableTests.cs
Tests/SacTests.cs
Tests/SuperStreamConsumerTests.cs
Tests/SuperStreamProducerTests.cs
Tests/SystemTests.cs
Tests/Utils.cs

Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/173 Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/171
Refactor class names. 
---
Why?
--
The idea is to give a similar [JavaStream client](https://github.com/rabbitmq/rabbitmq-stream-java-client) user experience.
Main concepts:
---
| Class  | Description  | How to get  | Note | 
|---|---|---|---|
|  RawProducer | Low-Level producer   |  `system.CreateRawProducer(new RawProducerConfig("stream")` | |
|  RawSuperStreamProducer | Low Level Super Stream Producer   |  `system.RawCreateSuperStreamProducer(new RawSuperStreamProducerConfig("superStream")` | |
|  Producer    | Hight Level producer. | `Producer.Create(new …

Refactor Classes names

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/StreamSystem.cs

Misc fixes related to style.
Basically prefixing private variables in select classes with `_`.

Fix style in select classes to be more dotnet-like

---

RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingWrite.cs

From MS sources:
```csharp
public virtual byte[] Encoding.GetBytes(string s)
{
if (s == null)
throw new ArgumentNullException(nameof(s),
SR.ArgumentNull_String);
int byteCount = GetByteCount(s);
byte[] bytes = new byte[byteCount];
int bytesReceived = GetBytes(s, 0, s.Length, bytes, 0);
Debug.Assert(byteCount == bytesReceived);
return bytes;
}
```
So `GetBytes(string).Length` call is pointless.

GetBytes(string).Length -> GetByteCount(string) + stackalloc in ReadString

---

RabbitMQ.Stream.Client.PerfTest/Program.fs
RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingWrite.cs
RabbitMQ.Stream.Client/AMQP/Data.cs
RabbitMQ.Stream.Client/AMQP/DescribedFormatCode.cs
RabbitMQ.Stream.Client/AMQP/Map.cs
RabbitMQ.Stream.Client/AMQP/Properties.cs
RabbitMQ.Stream.Client/Message.cs
RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/Publish.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/Subscribe.cs
RabbitMQ.Stream.Client/WireFormatting.cs

Improve the publish
- replace `seq.Slice(offset)` with `seq[offset..]`
- Add AggressiveInlining to the main send functions
- Add AggressiveInlining to write functions
- Tune the performance test increasing the messages buffer ( important to increase the throughout) 
With the 1.0.0-rc.6 version: 
Run the `RabbitMQ.Stream.Client.PerfTest`:
```
published 782590 msg/s in 8393 publish frames, confirmed 782590 msg/s, consumed: 782590 msg/sec total confirm frames 4140 4146 pending commands: 10000
published 845984 msg/s in 9077 publish frames, confirmed 845984 msg/s, consumed: 850080 msg/sec total confirm frames 4437 4443 pending commands: 10000
published 850967 msg/s in 9103 publish frames, confirmed 850967 msg/s, consumed: 848497 msg/sec total confirm frames 4726 4732 pending commands: 10000 …
```

replace seq.Slice(offset) with seq[offset..] 

---

RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs

Small improvement, the `GetAwaiter().GetResult();` will wait for the complete task. it takes the memory under control.
cc @ricardSiliuk @ricsiLT

Add GetAwaiter().GetResult(); on MessageHandler

---

RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/SuperStreamConsumer.cs
Tests/SuperStreamConsumerTests.cs

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/186
How to test:
---
Execute the Java producer as described [here](https://github.com/acogoluegnes/rabbitmq-stream-single-active-consumer) 
```
./mvnw -q -e  compile exec:java -Dexec.mainClass=com.rabbitmq.stream.SuperStreamProducer
```
Then execute the dotnet code:
```csharp
public static async Task Start()
{
var config = new StreamSystemConfig();
var system = await StreamSystem.Create(config);
var instanceName = "dn-instance-1";
var reference = "dn-my-app";
var consumer = Consumer.Create(new ConsumerConfig(system, "invoices")
{
IsSuperStream = true,
IsSingleActiveConsumer = true,
Reference = reference,
ConsumerUpdateListener = async (consumerRef, stream, arg3) =>
{
Console.WriteLine("ConsumerUpdateListener called"); …
```

Add SuperStream consumer info

---

RabbitMQ.Stream.Client/AddressResolver.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
Tests/UnitTests.cs

Add AddressResolver(EndPoint endPoint) in this way can accept DNS and IP endpoints
See also https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/188
you can now use:
```csharp
var addressResolver = new AddressResolver(new IPEndPoint(IPAddress.Parse("192.168.10.99"), 5552));
```          
and
```csharp
var addressResolver = new AddressResolver(new DnsEndPoint("MyDnsEntryPoint", 5552));
```    

Make the AddressResolver more generic

---

RabbitMQ.Stream.Client/RawConsumer.cs

- Add the consumer name property.
- Property is needed anyway no only in case of super stream

Add consumer name property

---

RabbitMQ.Stream.Client/RawConsumer.cs

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/205
In this way, the thread is not locked, and the:
```csharp
new MessageContext(message.MessageOffset, TimeSpan.FromMilliseconds(chunk.Timestamp)),
message).Wait(_token);
```
is in wait(...), so there is not the thread pool exhaustion.
@ricardSiliuk @ricsiLT it should not change anything. Please feel free to add any comments.
@jonnepmyra  do you have a chance to test it? 

Add cancellation token during subscribe

---

.ci/install.ps1
.ci/versions.json
.github/workflows/build-test.yaml
RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
Tests/FromToAMQPTests.cs
Tests/Tests.csproj

- Change the string read: use the offset len from the protocol instead
of encoding.GetByteCount(value). In some case the message properties can't be UFT8.
- Use Encoding.ASCII.GetString in case of FormatCode.Sym8, that's more correct.
- Add the AMQPlite dependency on the Test package to simulate the use case where the
parser failed.
The issue was reported by @thorhalvor 
To stimulate the issue ,you need to send a message using the [AMQP 1.0 client](https://github.com/Azure/amqpnetlite):
```csharp
var address = new Address("amqp://guest:guest@localhost:5672");
var connection = new Connection(address);
var session = new Session(connection);
Message message = new Message("A");
message.Properties = new Properties()
{
MessageId = "1",
Subject = "test",
ContentType = "text/plain"
}; …
```

Fix the read in the AMQP parser

---

RabbitMQ.Stream.Client/RoutingClient.cs

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/218

Decode the address type

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
Tests/MultiThreadTests.cs
Tests/RawProducerSystemTests.cs
kubernetes/stream_cluster.yaml

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/220 and part of https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/145
How to reproduce the issue:
---
See https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/221#issuecomment-1408242039
Important:
- Server has to be remote
- the body needs to be bigger than 3k
Main changes:
---
- Make the `WriteCommand` Async:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/5c695ef3862dd2f6ec0b72c52570e9c282a0ef34/RabbitMQ.Stream.Client/Connection.cs#L99-L114
Remove sync Waits (because of https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2012) :
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/5c695ef3862dd2f6ec0b72c52570e9c282a0ef34/RabbitMQ.Stream …

Handle System.InvalidOperationException in case of big body buffer send

---

RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/Deliver.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
Tests/RawConsumerSystemTests.cs

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/226 

Handle multi types in the stream

---

.editorconfig
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Compression.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/HeartBeatHandler.cs
RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/RasSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/RoutingClient.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/.editorconfig
Tests/ClientTests.cs
Tests/Utils.cs

The changes in https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/230 were good but not enough to fix deadlocks when trying to close consumers connections.
Adding a `ConfigureAwait(false)` _only_ to `MaybeClose` was not enough because when it was being called by `RawConsumer.Close` like this:
```C#
await _client.MaybeClose($"_client-close-subscriber: {_subscriberId}");
```
A deadlock was still happening.
The `ConfigureAwait` in .NET is kind of... eeh.. stupid. You basically have to call it for **every** `await` you do inside library code because, other wise, you would be getting the application's `SynchronizationContext`. Since this code is supposed to be used anywhere, we don't actually know how the client `SynchronizationContext` works, we don't know it's limitations. If it …

ConfigureAwait(false) for close stream/consumer/producer, query offset and create producer

---

.editorconfig
Examples/SuperStream/SuperStreamConsumer.cs
Examples/SuperStream/SuperStreamProducer.cs
RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Compression.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/HeartBeatHandler.cs
RabbitMQ.Stream.Client/MetaData.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RasSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/RoutingClient.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/.editorconfig
Tests/ClientTests.cs
Tests/MultiThreadTests.cs
Tests/ReliableTests.cs
Tests/Utils.cs

Handle some edge cases where the producer or consumer could go into a deadlock waiting for the semaphore.
Add the Cancellation token producer side and call the token cancellation when the producer and the consumer are forced to disconnect.
I did this [CaosTest](https://github.com/Gsantomaggio/rabbitmq-utils/tree/master/client_caos/Caos) for the stream client.
Where the connections are closed randomly.
```
Messages sent: 344800 -Messages confirmed: 227737 - Messages error: 1024 - Total 228761  Messages consumed: 169337
Messages sent: 397000 -Messages confirmed: 279919 - Messages error: 116082 - Total 396001  Messages consumed: 206422
```
Client should be able to reconnect and continue to produce and consume 

Improve the reconnect

---

RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs
Tests/FromToAMQPTests.cs

Fix the read boolean. The offeset is moved corretly. Add test for this use case.

Small Fix read boolean

---

RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/Reliable/DeduplicatingProducer.cs
RabbitMQ.Stream.Client/Reliable/DeduplicationProducer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
Tests/DeduplicationProducerTests.cs
Tests/MultiThreadTests.cs
Tests/ReliableTests.cs
Tests/Utils.cs

Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/227
Implement the `DeduplicationProducer` make the `ProducerConfig.Reference` deprecated.
The `Producer` does not need the `Reference` to work. `Reference` is needed only for the Deduplication part.
The low-level Class is the `RawProducer` class; this class sets the correct parameters to enable the deduplication and to make it easy to use. 

Implement Deduplicating Producer

---

.github/workflows/build-test.yaml
.github/workflows/publish-nuget.yaml
Build.csproj
Directory.Build.props
Directory.Build.targets
Directory.Packages.props
Examples/Performances/Performances.csproj
Makefile
NuGet.Config
RabbitMQ.Stream.Client.PerfTest/Directory.Build.targets
RabbitMQ.Stream.Client.PerfTest/RabbitMQ.Stream.Client.PerfTest.fsproj
RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
Tests/Tests.csproj
build.bat
build.ps1
docs/Documentation/Documentation.csproj
docs/SuperStream/SuperStream.csproj
global.json
run-test.bat

Inspired by:
* https://github.com/StackExchange/StackExchange.Redis
* https://www.ethan-shea.com/posts/setting-up-dotnet-2021
* https://devblogs.microsoft.com/nuget/introducing-central-package-management/

Use various modern dotnet build files

---

RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamStats.cs
Tests/SystemTests.cs

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/257

Convert functions result form long to ulong

---

RabbitMQ.Stream.Client/StreamSystem.cs

Hi,
`Random.Shared` is already used in other places in the codebase and I don't see any reasons why it should not be used here.

Switch to Random.Shared

---

RabbitMQ.Stream.Client/Consts.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
Tests/RawConsumerSystemTests.cs

ref: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/264

Expose initial credits configuration

---

Directory.Packages.props

This PR attempts to match the target framework version with similar versioned dependencies. 
When using this library in a .Net 6 project I was running into NU1109 build errors: 
```
error NU1109: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 7.0.0 to centrally defined 6.0.1. Update the centrally managed package version to a higher version. 
```

Adjust dependencies for multi-targeting 

---

RabbitMQ.Stream.Client/RawConsumer.cs

Bug in DEBUG level log statement for creation of `RawConsumer`. Occurs only when DEBUG level was specified for the consumer. Confirmed using the following:
```
var factory = LoggerFactory.Create(builder =>
{
builder.AddSimpleConsole();
builder.AddFilter("RabbitMQ.Stream", LogLevel.Debug);
});
...
var consumerLogger = factory.CreateLogger<Consumer>();
var consumer = await system.CreateRawConsumer(
new RawConsumerConfig(stream)
{
Reference = "consumer",
MessageHandler = async (consumer, ctx, message) =>
{
await Task.CompletedTask;
}
}, consumerLogger);
```

Fix RawConsumer bug in DEBUG log statement causing exceptions

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/SystemTests.cs
docs/Documentation/StreamSystemUsage.cs
docs/asciidoc/api.adoc

Support External SALS Auth
How to test:
--------------
```csharp
var ssl = new SslOption()
{
Enabled = true,
ServerName = "my_server_name",
CertPath = "certs/client/keycert.p12",
CertPassphrase = null,
CertificateValidationCallback = (sender, certificate, chain, errors) => true,
};
var config = new StreamSystemConfig()
{
UserName = "user_does_not_exist",
Password = "password_does_not_exist",
Ssl = ssl,
Endpoints = new List<EndPoint>(new List<EndPoint>()
{
new DnsEndPoint("my_server_name", 5551)
}),
AuthMechanism = AuthMechanism.External,
};
const string stream = "test-stream";
var system = await StreamSystem.Create(config);
await system.CreateStream(new StreamSpec(stream));
Console.WriteLine("Stream created");
```
Docker image:
```
pivotalrabbitmq/rabbitmq:v3.12.x-otp-max-bazel
```
or …

Support External SASL configuration

---

RabbitMQ.Stream.Client/Connection.cs

In a pressure system, the process frame could take more time to be closed. 
This PR increase a bit the wait time and change the log from Error to Warning because it is not actually an error just a warning.

change default log for ProcessIncomingFrames thread

---

RabbitMQ.Stream.Client/RawConsumer.cs
Tests/FromToAMQPTests.cs

Add more info during the error parse message.
Add more tests form messages coming from `AMQP 0_9_1`

Add more info during the error parse message

---

RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/ICrc32.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
Tests/Crc32.cs
Tests/RawConsumerSystemTests.cs
Tests/ReliableTests.cs
Tests/SuperStreamConsumerTests.cs
Tests/Tests.csproj

If a library user wishes to have Crc32 checking, they must implement the `ICrc32` interface and set an implementation on the configuration.
References:
* #19
* #285

Add ICrc32 interface

---

RabbitMQ.Stream.Client/AvailableFeatures.cs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Consts.cs
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
docs/StreamFilter/StreamFilter/FilterConsumer.cs
docs/StreamFilter/StreamFilter/FilterProducer.cs
docs/StreamFilter/StreamFilter/README.md
docs/asciidoc/advanced-topics.adoc

- Add more debug info to better understand the startup step.
- print the server properties 
Releated to https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/299

Add debug info during the login step

---

RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Subscribe.cs

I guess at minimum I'd like docs merged - the additional constructors are optional but would help out.
Essentially, I consider existing constructor to be a bit of a foot-gun - I only realized that giving normal timestamp didn't work properly because I've read a bug report here :D

Add docs to timestamp offset; add additional constructors

---

RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
Tests/RawConsumerSystemTests.cs
Tests/ReliableTests.cs

- Add DateTimeOffset test. The test is not 100% perfect since it depends on the data time starting. In this case, the test returns all the messages. 
- Constant naming refactor.

Add DateTimeOffset test

---

Makefile
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/FilterTest.cs
Tests/RawProducerSystemTests.cs
Tests/SuperStreamConsumerTests.cs

Fixes #296
It is common to have a local instance of RabbitMQ running locally,
either via a local rabbit (e.g. installed from source), or inside a
container (e.g. Docker or local Kubernetes). In both cases, our client
may not work without providing an address resolver, or without changing
the advertised host/port in rabbit via an env variable. Specifically,
our clients won't work if the client can't resolve the hostname of the
local machine.
For exampe, a laptop may have a hostname mylaptop.some-company.com.
Rabbit won't be impacted as long as it works in a single-node
configuration. However, the client smart features to locate the stream
leaders and replicas will get "confused" because it can't resolve the
hostname.
This commit changes the smart layer, so that it won't try to locate the …

Force localhost connections when client connects to localhost

---

RabbitMQ.Stream.Client/Reliable/Producer.cs

Found an unused internal class in Producer.cs. Unless there is a future use for this, it is not needed. But the naming seems to indicate that this was test code.

Removed unused class MyMethodAttribute from Producer.cs

---

.ci/install.ps1
.github/workflows/build-test.yaml
Makefile
RabbitMQ.Stream.Client/RoutingClient.cs
Tests/ReliableTests.cs
Tests/Resources/definition_test.json
Tests/UnitTests.cs
Tests/Utils.cs
Tests/xunit.runner.json

Speed up a bit the tests
- reduce the collect management time, it reduces the time to wait for the HTTP calls
- remove some wait since there is already the wait_until function
- remove the load definition and use the AMQP client to create the super-stream configuration

Improve test speed

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/EntityInfo.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/DeduplicatingProducer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
Tests/RawConsumerSystemTests.cs

The call returns the Reference and Stream.
So that you know, the `Reference` is deprecated for the producer class and will be removed at some point. So the `info.reference` for the producer will also be removed.
We can add other info about the consumer and producer and the consumer in the future.
ref: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/321 
To get the info:
```csharp
var consumer = await Consumer.Create(new ConsumerConfig(system, "MyStream") { Reference = "consumer", });
entityInfo = consumer.Info;
Assert.Equal("MyStream", entityInfo.Stream);
Assert.Equal("consumer", entityInfo.Reference);
``` 
and also in the handler:
```csharp
MessageHandler = async (sourceStream, consumer, ctx, message) =>
{
Console.WriteLine($"Consumer info Reference: …
```

Add Info class to the Producer/Consumer classes

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/EntityInfo.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/DeduplicatingProducer.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
Tests/RawConsumerSystemTests.cs

Per conversation with @Zerpet
it is better to have info class for each type so we can specialize them adding more info about  Producer or Consumer

Make the info class abstract

---

RabbitMQ.Stream.Client/Client.cs

ToUpper is not enough, we need to use InvariantCulture to be sure that the string is converted to uppercase in a way that is consistent with the server.

Fix connections to server on different locales

---

.github/workflows/build-test.yaml
RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/RoutingClient.cs
Tests/ClientTests.cs
Tests/ConnectionsPoolTests.cs

With this PR https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/328 the client can handle multi-producers and consumers per connection.
This PR removes [`MetadataHandler`](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/332/files#diff-71215640c5968601ad0a124946241692beb3c931cc450bb43bb7061e8f84c47eL56)  and introduces [`OnMetadataUpdate`](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/332/files#diff-71215640c5968601ad0a124946241692beb3c931cc450bb43bb7061e8f84c47eR58
) event.
The event can handle multiple Metadata updates coming from the server. Metadata update is raised when a stream is deleted, or a replica is removed. 
The server automatically removes the producers and consumers linked to the connection, here we need to remove these entities …

New event to handle Metadata update

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
Tests/EntitiesStateTests.cs
Tests/MultiThreadTests.cs
Tests/ReliableTests.cs
Tests/SuperStreamProducerTests.cs

The pr is part of https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/336 the aim is to standardise the behaviour.
- Add AlreadyClosedException when a producer or super stream producer is closed In the same way like AMQP does with channels
- Producer: Flush the pending messages when closed.
- Producer: Add AlreadyClosedException when closed. So it is the same like: AMQP and RawProducer and RawSuperStreamProducer
- Improve IsAKnownException function with the AggregateException that can contains known exceptions needed for reconnect the client
- Add EntitiesStateTests to test all the status and verify that all the entities have the same behaviour

Improve the rawProducer and rawSuperStreamProducer status

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/Subscribe.cs
Tests/ClientTests.cs
Tests/ConnectionsPoolTests.cs

* During the handle delivery, the consumer could receive a Token cancellation
In this commit, the consumer handles it with a log and exit. It will avoid
propagating the error and close the TCP connection
* Add a lock around the IsOpen() function to make it thread-safe.
In normal situations, it does not matter. It is useful when a consumer is
created and destroyed in a short time
* Handle the Subscribe error. In case there is an error during the init.
The error will be raised to the caller, but the pool must be consistent.
Found the issue with a caos test like:
```csharp
for (var z = 0; z < 800; z++)
{
Console.WriteLine($"Starting consumer test {z}");
await Task.Delay(new Random().Next(100, 200));
try
{
var tcs = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously); …
```

Handle cancellation token during the consumer close

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/IClient.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/RoutingClient.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ClientTests.cs
Tests/ConnectionsPoolTests.cs
Tests/PermissionTests.cs
Tests/RawConsumerSystemTests.cs
Tests/RawProducerSystemTests.cs
Tests/ReliableTests.cs
Tests/UnitTests.cs
docs/Documentation/RawClasses.cs
kubernetes/stream_cluster.yaml

* Part of https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/336
* Improve the disconnection message. It is possible to understand if it is a normal disconnection or an unexpected.
* Remove the Active Items from the connection pool and use the Publishers and Consumers client list directly to check the pool size
* Refactor the Factory Classes. Remove code duplication in case of metadata update and connection closed. See ReliableBase.OnEntityClosed
* Handle streamNotAvailable error. In this case the client will try to reconnect the entity
* Fix the events attach to the RawConsumer and RawProducer. The events are attached only if the ResponseCode is OK
* Detach the events once the entity receives the disconnection or metadata update. In that case, the entity is closed
* …

Improve Reconnection

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/IClient.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/RoutingClient.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/RawConsumerSystemTests.cs
Tests/ReliableTests.cs
Tests/SuperStreamConsumerTests.cs
Tests/SuperStreamProducerTests.cs
Tests/UnitTests.cs
Tests/Utils.cs

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/333
Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/335
The PR is focused on making the client more stable during the server restart and better handling the metadata update event.
Most of the changes are in the super stream producer and consumer.
See the issue https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/333
The RawSuperStreamProducer and RawSuperStreamConsumer expose two callbacks:
- `ConnectionClosedHandler (reason, stream)` 
- `MetadataHandler(update)` 
- `ISuperStreamProducer` and `ISuperStreamConsumer` interfaces 
ConnectionClosedHandler
--
The callback is raised each time a partition is closed for some reason. You can check the reason with:
```
1- public …
```

Improve the super stream reconnection

---

RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/IReconnectStrategy.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ReliableTests.cs
Tests/SuperStreamConsumerTests.cs
Tests/SuperStreamProducerTests.cs
Tests/Utils.cs

Per conversation with @acogoluegnes we want to have (more or less) the same Stream Java Client behaviour. 
* The back-off reconnect strategy is increased sensibly. The previous value was too aggressive. It caused a lot of tentative and a lot of server requests. The TCP port can be ready during the restart, but the stream cannot be ready due to the sync.
* Introduce a random delay on the strategy to avoid having the same reconnection time in case the client has more producers and consumers.
* Introduce also a random delay on the disconnected part on disconnect for the same above reason.
* Fixes a bug: check the leader during the reconnection partition.
* Introduce the TestBackOff strategy for the tests. The default value is too high for the tests

Increase the backoff strategy time

---

RabbitMQ.Stream.Client/AbstractEntity.cs
RabbitMQ.Stream.Client/EntityInfo.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/IProducer.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/RawProducer.cs
RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/Producer.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/RawConsumerSystemTests.cs
Tests/ReliableTests.cs
Tests/SuperStreamConsumerTests.cs
Tests/SuperStreamProducerTests.cs

The Identifier helps to correlate the entities with the logs and the UI.
Add the Identifier for producer and consumer. For the consumer is visible in the UI, like:
Code:
```csharp
var producer = await Producer.Create(new ProducerConfig(system, stream)
{
Identifier = $"my_producer_99",
```
logs:
```
ProducerInfo(Stream=my_stream, Reference=, Identifier=my_producer_99)
````
Note: The producer doesn't have custom properties so won't be showed on the UI.

Add Producer/Consumer Identifier

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/IClient.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/SystemTests.cs
Tests/UnitTests.cs

add update secret functionality.
add test for UpdateSecret function.
Solves #340  with the introduction of the UpdateSecret method in StreamSystem. 
Usage example:
```csharp
await streamSystem.UpdateSecret("new_secret");
```

Update secret functionality

---

RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
Tests/RawConsumerSystemTests.cs
docs/ReliableClient/Program.cs

Closes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/331

Add Chunk info consumer side

---

RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/RawSuperStreamProducer.cs
docs/ReliableClient/Program.cs
docs/ReliableClient/RClient.cs

Remove code duplication to handle the pool

---

README.md
RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamSpec.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/SystemTests.cs
Tests/Utils.cs
docs/ReliableClient/BestPracticesClient.cs
docs/ReliableClient/Program.cs
docs/ReliableClient/README.md
docs/ReliableClient/ReliableClient.csproj
docs/ReliableClient/appsettings.json
docs/SuperStream/Costants.cs
docs/SuperStream/README.md
docs/SuperStream/Start.cs
docs/SuperStream/SuperStreamProducer.cs
docs/SuperStream/SuperStreamProducerKey.cs

- Add documentation
- Add configuration to BestPracticesClient client

Add super stream exists API

---

RabbitMQ.Stream.Client/StreamSystem.cs

When a loopback address is specified, use it directly instead of using `localhost`.
Because DNS resolution on `localhost` may resolve to IPV6 (`::1`), although the user may have expected an IPV4 loopback address (`127.0.0.1`).
Resolved #374 & #375

Use user defined loopback address if available (#374)

---

RabbitMQ.Stream.Client/Reliable/DeduplicatingProducer.cs
Tests/FilterTest.cs

Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/382

Add filter for deduplication producer

---

RabbitMQ.Stream.Client/ClientExceptions.cs
RabbitMQ.Stream.Client/ConnectionsPool.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/ClientTests.cs
Tests/ConnectionsPoolTests.cs
Tests/UnitTests.cs
docs/asciidoc/api.adoc

Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/388

Add Connection Pool Close configuration

---

RabbitMQ.Stream.Client/Client.cs
RabbitMQ.Stream.Client/Connection.cs
RabbitMQ.Stream.Client/HeartBeatHandler.cs
RabbitMQ.Stream.Client/PublicAPI.Shipped.txt
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/Reliable/ProducerFactory.cs
RabbitMQ.Stream.Client/Reliable/ReliableBase.cs
Tests/UnitTests.cs
docs/ReliableClient/BestPracticesClient.cs

Close from normal to Unexpected.
Fixes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/393
Changes:
Remove the update status form the the Dispose() function.
It is unnecessary since the disposal can be called only from the Client close() function
where the status is set.
Add a function to convert the connection close reason string to the Reliable.ChangeStatusReason Enum.
This mapping should be improved to version 2.0, where we can introduce breaking changes.
In version 1.x, we need the conversion function.

Handle too many heart missing with reconnection 

---

RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs

This change ensures that the reliable consumer tracks the lastOffsetConsumed correctly, allowing it to reconnect to the correct offset in the event of a reconnection.
**Before this PR:**
The lastOffsetConsumed was recorded before the message handler was executed, which could result in potential message loss during connection issues or consumer reconnections.
**After this PR:**
The lastOffsetConsumed will be stored after the message handler is executed, preventing message loss in the event of connection issues or reconnections.

Last offset fix

---

RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/SystemTests.cs

Expose Store offset to stream system

Expose Store offset to stream system 

---

Directory.Packages.props
README.md
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/StreamSystem.cs
Tests/RawConsumerSystemTests.cs
Tests/SystemTests.cs
docs/SingleActiveConsumer/Program.cs
docs/SingleActiveConsumer/SaCProducer.cs
docs/SingleActiveConsumer/SacConsumer.cs
docs/SingleActiveConsumer/SingleActiveConsumer.csproj
docs/asciidoc/api.adoc
docs/asciidoc/query-stream.adoc

Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/370

Add TryQueryOffset API

---

RabbitMQ.Stream.Client/Consts.cs
RabbitMQ.Stream.Client/IConsumer.cs
RabbitMQ.Stream.Client/ICrc32.cs
RabbitMQ.Stream.Client/PublicAPI.Unshipped.txt
RabbitMQ.Stream.Client/RawConsumer.cs
RabbitMQ.Stream.Client/Reliable/Consumer.cs
RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs
RabbitMQ.Stream.Client/StreamCrc32.cs
Tests/Crc32Tests.cs
Tests/FlowControlTests.cs
docs/Documentation/ConsumerUsage.cs
docs/Documentation/SetFlowControl.cs
docs/ManualCredits/ManualCredits.csproj
docs/ManualCredits/Program.cs
docs/asciidoc/api.adoc

Add Consumer Flow control.
Configure the way to request the credits with the following parameters:
```csharp
public enum ConsumerFlowStrategy
{
CreditsBeforeParseChunk,
CreditsAfterParseChunk,
ConsumerCredits
}
var consumerConfig = new RawConsumerConfig(stream)
{
FlowControl = new FlowControl() { 
Strategy = ConsumerFlowStrategy.CreditsBeforeParseChunk
},
```
Add `rawConsumer.Credits` to manually request `Credits`
Closes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/420

Add consumer flow control

---

RabbitMQ.Stream.Client/Reliable/DeduplicatingProducer.cs
Tests/DeduplicationProducerTests.cs

When creating a DeduplicatingProducer and adding any event to DeduplicatingProducerConfig.StatusChanged. At this point, this event is simply lost and is not processed further.

Fixed forwarding of StatusChanged event
